su -c "sudo apt-get update"
su -c "sudo apt install -y espeak ffmpeg libespeak1"
su -c "sudo apt-get install -y libsndfile1-dev"
su -c "pip3 install newspaper3k"
su -c "pip3 install pandas"
su -c "pip3 install simplejson"
su -c "pip3 install minet"
su -c "pip3 install dotenv"
su -c "pip3 install spacy"
su -c "pip3 install supervisor"
su -c "pip3 install nltk"
su -c "pip3 install lxml"
su -c "pip3 install textblob"
su -c "pip3 install spacytextblob"
su -c "pip3 install vaderSentiment"
su -c "pip3 install TTS"
su -c "python3 -m spacy download en_core_web_md"
su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data punkt"
su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data stopwords"
su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data vader_lexicon"
su -c "python3 -m textblob.download_corpora"
