name: CI

on:
  push:
    branches:
      - master

jobs:
  build-test:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5 # or alternative dependency management
      - uses: php-actions/phpunit@v3
